export const lightTokens = {
    colors: {
        background: '#F9F9F9',
        surface: '#FFFFFF',
        surface2: '#F0F0F0',
        border: '#E0E0E0',
        textPrimary: '#0A0A0A',
        textMuted: '#6B6B6B',
        accent: '#E63946',
        accentForeground: '#FFFFFF',
        success: '#22C55E',
        danger: '#E63946',
        tabBar: '#FFFFFF',
        tabBarBorder: '#E0E0E0',
    },
    spacing: {
        xs: 4,
        sm: 8,
        md: 12,
        lg: 16,
        xl: 20,
        '2xl': 24,
        '3xl': 32,
        '4xl': 40,
        '5xl': 48,
    },
    radius: {
        sm: 0,
        md: 0,
        lg: 0,
        full: 9999,
    },
    fontSize: {
        xs: 11,
        sm: 12,
        base: 14,
        md: 16,
        lg: 18,
        xl: 22,
        '2xl': 28,
        '3xl': 34,
    },
    fontWeight: {
        regular: '400' as const,
        medium: '500' as const,
        semiBold: '600' as const,
        bold: '700' as const,
        extraBold: '800' as const,
    },
    lineHeight: {
        tight: 1.2,
        normal: 1.5,
        relaxed: 1.3,
    },
    letterSpacing: {
        tight: -0.3,
        normal: 0,
        wide: 0.3,
    },
};

export const darkTokens = {
    colors: {
        background: '#0A0A0A',
        surface: '#141414',
        surface2: '#1E1E1E',
        border: '#2A2A2A',
        textPrimary: '#F5F5F5',
        textMuted: '#888888',
        accent: '#E63946',
        accentForeground: '#FFFFFF',
        success: '#22C55E',
        danger: '#E63946',
        tabBar: '#141414',
        tabBarBorder: '#2A2A2A',
    },
    spacing: {
        xs: 4,
        sm: 8,
        md: 12,
        lg: 16,
        xl: 20,
        '2xl': 24,
        '3xl': 32,
        '4xl': 40,
        '5xl': 48,
    },
    radius: {
        sm: 0,
        md: 0,
        lg: 0,
        full: 9999,
    },
    fontSize: {
        xs: 11,
        sm: 12,
        base: 14,
        md: 16,
        lg: 18,
        xl: 22,
        '2xl': 28,
        '3xl': 34,
    },
    fontWeight: {
        regular: '400' as const,
        medium: '500' as const,
        semiBold: '600' as const,
        bold: '700' as const,
        extraBold: '800' as const,
    },
    lineHeight: {
        tight: 1.2,
        normal: 1.5,
        relaxed: 1.3,
    },
    letterSpacing: {
        tight: -0.3,
        normal: 0,
        wide: 0.3,
    },
};

export type ThemeTokens = typeof lightTokens;

